/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.asg.send_pulse;

import io.micronaut.runtime.Micronaut;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Micronaut.run(App.class, args);
    }
}
